# Generated by Django 6.1.1 on 2026-09-03 07:49

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('refunded_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('payment_status', models.CharField(choices=[('PENDING', 'Pending'), ('PAID', 'Paid'), ('FAILED', 'Failed'), ('REFUNDED', 'Refunded')], db_index=True, default='PENDING', max_length=10)),
                ('payment_method', models.CharField(choices=[('CASH', 'Cash'), ('CARD', 'Card'), ('ESEWA', 'eSewa'), ('KHALTI', 'Khalti'), ('BANK_TRANSFER', 'Bank transfer')], default='CASH', max_length=20)),
                ('transaction_reference', models.CharField(blank=True, db_index=True, default='', max_length=100)),
                ('paid_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='bookings.booking')),
            ],
            options={
                'db_table': 'payments_payment',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['payment_status', 'paid_at'], name='payments_pa_payment_7272e5_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('amount__gte', 0)), name='payment_amount_non_negative')],
            },
        ),
    ]
