# Generated by Django 5.2.17 on 2026-09-11 10:42

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('full_name', models.CharField(help_text="Customer's full name", max_length=200)),
                ('title', models.CharField(help_text="Job title or role (e.g., 'Regular Player', 'Tournament Organizer')", max_length=200)),
                ('image', models.ImageField(blank=True, help_text='Customer photo', null=True, upload_to='testimonials/')),
                ('content', models.TextField(help_text='Testimonial content/review')),
                ('is_active', models.BooleanField(default=True, help_text='Show on website')),
                ('sort_order', models.IntegerField(default=0, help_text='Display order (lower numbers first)')),
            ],
            options={
                'verbose_name': 'Testimonial',
                'verbose_name_plural': 'Testimonials',
                'db_table': 'cms_testimonial',
                'ordering': ['sort_order', '-created_at'],
            },
        ),
    ]
