# Generated by Django 5.2.17 on 2026-09-10 10:54

import common.storages
import common.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArenaHighlight',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key', models.CharField(db_index=True, max_length=50, unique=True)),
                ('icon', models.CharField(blank=True, help_text="Icon name (e.g., 'sparkles', 'zap')", max_length=50, null=True)),
                ('text', models.CharField(max_length=200)),
                ('sort_order', models.PositiveIntegerField(db_index=True, default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Arena Highlight',
                'verbose_name_plural': 'Arena Highlights',
                'db_table': 'cms_arena_highlight',
                'ordering': ['sort_order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='ArenaImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key', models.CharField(db_index=True, max_length=50, unique=True)),
                ('image', models.ImageField(storage=common.storages.image_storage, upload_to='cms/arena/', validators=[common.validators.validate_image_upload])),
                ('alt_text', models.CharField(max_length=200)),
                ('sort_order', models.PositiveIntegerField(db_index=True, default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Arena Image',
                'verbose_name_plural': 'Arena Images',
                'db_table': 'cms_arena_image',
                'ordering': ['sort_order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='ArenaSection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('eyebrow', models.CharField(default='The Arena', max_length=50)),
                ('heading', models.CharField(default='One arena. Built for the game.', max_length=100)),
                ('description', models.TextField()),
                ('since_label', models.CharField(default='Since 2018', max_length=50)),
            ],
            options={
                'verbose_name': 'Arena Section',
                'verbose_name_plural': 'Arena Section',
                'db_table': 'cms_arena_section',
            },
        ),
        migrations.CreateModel(
            name='CTABannerSection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('heading', models.CharField(default="Gather your squad. We'll keep the lights on.", max_length=200)),
                ('description', models.TextField()),
                ('primary_cta_label', models.CharField(default='Book a Slot', max_length=50)),
                ('primary_cta_href', models.CharField(default='/bookings', max_length=200)),
                ('primary_cta_style', models.CharField(default='secondary', max_length=20)),
                ('secondary_cta_label', models.CharField(default='Contact Us', max_length=50)),
                ('secondary_cta_href', models.CharField(default='/contact', max_length=200)),
                ('secondary_cta_style', models.CharField(default='outline', max_length=20)),
            ],
            options={
                'verbose_name': 'CTA Banner Section',
                'verbose_name_plural': 'CTA Banner Section',
                'db_table': 'cms_cta_banner_section',
            },
        ),
        migrations.CreateModel(
            name='FeatureItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key', models.CharField(db_index=True, max_length=50, unique=True)),
                ('icon', models.CharField(help_text='Icon name', max_length=50)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('sort_order', models.PositiveIntegerField(db_index=True, default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Feature Item',
                'verbose_name_plural': 'Feature Items',
                'db_table': 'cms_feature_item',
                'ordering': ['sort_order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='FeaturesSection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('eyebrow', models.CharField(default='Why Nexus', max_length=50)),
                ('heading', models.CharField(default='Everything a player needs', max_length=100)),
            ],
            options={
                'verbose_name': 'Features Section',
                'verbose_name_plural': 'Features Section',
                'db_table': 'cms_features_section',
            },
        ),
        migrations.CreateModel(
            name='GalleryPreviewPhoto',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key', models.CharField(db_index=True, max_length=50, unique=True)),
                ('image', models.ImageField(storage=common.storages.image_storage, upload_to='cms/gallery/', validators=[common.validators.validate_image_upload])),
                ('alt_text', models.CharField(max_length=200)),
                ('aspect_ratio', models.CharField(default='4/3', help_text="e.g., '4/3', '16/9', '1/1'", max_length=10)),
                ('sort_order', models.PositiveIntegerField(db_index=True, default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Gallery Preview Photo',
                'verbose_name_plural': 'Gallery Preview Photos',
                'db_table': 'cms_gallery_preview_photo',
                'ordering': ['sort_order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='GalleryPreviewSection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('eyebrow', models.CharField(default='Gallery', max_length=50)),
                ('heading', models.CharField(default='Straight off our turf', max_length=100)),
                ('description', models.TextField()),
                ('count_label', models.CharField(default='+120 photos', max_length=50)),
                ('cta_label', models.CharField(default='View full gallery', max_length=50)),
                ('cta_href', models.CharField(default='/gallery', max_length=200)),
                ('cta_style', models.CharField(default='outline', max_length=20)),
            ],
            options={
                'verbose_name': 'Gallery Preview Section',
                'verbose_name_plural': 'Gallery Preview Section',
                'db_table': 'cms_gallery_preview_section',
            },
        ),
        migrations.CreateModel(
            name='HeroSection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('badge', models.CharField(default="Kathmandu's home of futsal", max_length=100)),
                ('title', models.CharField(default='Book your slot.', max_length=100)),
                ('title_highlight', models.CharField(blank=True, default='Own the game.', help_text='Highlighted part of the title (optional)', max_length=100)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, storage=common.storages.image_storage, upload_to='cms/hero/', validators=[common.validators.validate_image_upload])),
                ('image_alt', models.CharField(blank=True, max_length=200)),
                ('primary_cta_label', models.CharField(default='Book a Slot', max_length=50)),
                ('primary_cta_href', models.CharField(default='/bookings', max_length=200)),
                ('primary_cta_style', models.CharField(default='primary', max_length=20)),
                ('secondary_cta_label', models.CharField(default='Explore Gallery', max_length=50)),
                ('secondary_cta_href', models.CharField(default='/gallery', max_length=200)),
                ('secondary_cta_style', models.CharField(default='outline', max_length=20)),
            ],
            options={
                'verbose_name': 'Hero Section',
                'verbose_name_plural': 'Hero Section',
                'db_table': 'cms_hero_section',
            },
        ),
        migrations.CreateModel(
            name='HomepageMeta',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('meta_title', models.CharField(default='Nexus FMS — Book Your Futsal Slot Online', max_length=200)),
                ('meta_description', models.TextField(default='Premium futsal courts in Kathmandu. Check live availability and book your slot online in seconds — pay at the counter.', max_length=300)),
            ],
            options={
                'verbose_name': 'Homepage Meta',
                'verbose_name_plural': 'Homepage Meta',
                'db_table': 'cms_homepage_meta',
            },
        ),
        migrations.CreateModel(
            name='HowItWorksSection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('eyebrow', models.CharField(default='How it works', max_length=50)),
                ('heading', models.CharField(default='On the pitch in three steps', max_length=100)),
            ],
            options={
                'verbose_name': 'How It Works Section',
                'verbose_name_plural': 'How It Works Section',
                'db_table': 'cms_how_it_works_section',
            },
        ),
        migrations.CreateModel(
            name='HowItWorksStep',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key', models.CharField(db_index=True, max_length=50, unique=True)),
                ('icon', models.CharField(help_text='Icon name', max_length=50)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('sort_order', models.PositiveIntegerField(db_index=True, default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'How It Works Step',
                'verbose_name_plural': 'How It Works Steps',
                'db_table': 'cms_how_it_works_step',
                'ordering': ['sort_order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='StatItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key', models.CharField(db_index=True, max_length=50, unique=True)),
                ('value', models.CharField(max_length=50)),
                ('label', models.CharField(max_length=100)),
                ('sort_order', models.PositiveIntegerField(db_index=True, default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Stat Item',
                'verbose_name_plural': 'Stat Items',
                'db_table': 'cms_stat_item',
                'ordering': ['sort_order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key', models.CharField(db_index=True, max_length=50, unique=True)),
                ('quote', models.TextField()),
                ('name', models.CharField(max_length=100)),
                ('role', models.CharField(max_length=100)),
                ('avatar', models.ImageField(blank=True, null=True, storage=common.storages.image_storage, upload_to='cms/testimonials/', validators=[common.validators.validate_image_upload])),
                ('sort_order', models.PositiveIntegerField(db_index=True, default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Testimonial',
                'verbose_name_plural': 'Testimonials',
                'db_table': 'cms_testimonial',
                'ordering': ['sort_order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='TestimonialsSection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('eyebrow', models.CharField(default='Testimonials', max_length=50)),
                ('heading', models.CharField(default='What our players say', max_length=100)),
            ],
            options={
                'verbose_name': 'Testimonials Section',
                'verbose_name_plural': 'Testimonials Section',
                'db_table': 'cms_testimonials_section',
            },
        ),
    ]
