# Generated by Django 5.2.17 on 2026-09-10 11:07

import common.storages
import common.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingsBanner',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('eyebrow', models.CharField(default='Bookings', max_length=50)),
                ('title', models.CharField(default='Pick your date. Own your slot.', max_length=200)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, storage=common.storages.image_storage, upload_to='cms/bookings/', validators=[common.validators.validate_image_upload])),
                ('image_alt', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'verbose_name': 'Bookings Banner',
                'verbose_name_plural': 'Bookings Banner',
                'db_table': 'cms_bookings_banner',
            },
        ),
        migrations.CreateModel(
            name='BookingsHelpStrip',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('heading', models.CharField(default='Need a hand with your booking?', max_length=200)),
                ('description', models.TextField()),
                ('cta_label', models.CharField(default='Contact Us', max_length=50)),
                ('cta_href', models.CharField(default='/contact', max_length=200)),
                ('cta_style', models.CharField(default='outline', max_length=20)),
            ],
            options={
                'verbose_name': 'Bookings Help Strip',
                'verbose_name_plural': 'Bookings Help Strip',
                'db_table': 'cms_bookings_help_strip',
            },
        ),
        migrations.CreateModel(
            name='BookingsPageMeta',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('meta_title', models.CharField(default='Book a Slot — Nexus FMS', max_length=200)),
                ('meta_description', models.TextField(default='Check live slot availability and book your futsal court online. Pay at the counter — free rescheduling up to 12 hours before.', max_length=300)),
            ],
            options={
                'verbose_name': 'Bookings Page Meta',
                'verbose_name_plural': 'Bookings Page Meta',
                'db_table': 'cms_bookings_page_meta',
            },
        ),
        migrations.CreateModel(
            name='BookingsPoliciesSection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('heading', models.CharField(default='Good to know', max_length=100)),
            ],
            options={
                'verbose_name': 'Bookings Policies Section',
                'verbose_name_plural': 'Bookings Policies Section',
                'db_table': 'cms_bookings_policies_section',
            },
        ),
        migrations.CreateModel(
            name='BookingsPolicy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key', models.CharField(db_index=True, max_length=50, unique=True)),
                ('icon', models.CharField(help_text='Icon name', max_length=50)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('sort_order', models.PositiveIntegerField(db_index=True, default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Bookings Policy',
                'verbose_name_plural': 'Bookings Policies',
                'db_table': 'cms_bookings_policy',
                'ordering': ['sort_order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='BookingsRateRow',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key', models.CharField(db_index=True, max_length=50, unique=True)),
                ('title', models.CharField(max_length=100)),
                ('hours', models.CharField(help_text="e.g., '6 AM – 12 PM'", max_length=50)),
                ('weekday_price', models.PositiveIntegerField(help_text='Price in NPR')),
                ('weekend_price', models.PositiveIntegerField(help_text='Price in NPR')),
                ('highlight', models.BooleanField(default=False)),
                ('highlight_label', models.CharField(blank=True, help_text="e.g., 'Floodlit'", max_length=50)),
                ('sort_order', models.PositiveIntegerField(db_index=True, default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Bookings Rate Row',
                'verbose_name_plural': 'Bookings Rate Rows',
                'db_table': 'cms_bookings_rate_row',
                'ordering': ['sort_order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='BookingsRatesSection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('heading', models.CharField(default='Rates', max_length=100)),
                ('description', models.TextField()),
                ('weekday_label', models.CharField(default='Weekday', max_length=50)),
                ('weekend_label', models.CharField(default='Weekend', max_length=50)),
                ('refreshments_note', models.TextField()),
                ('events_title', models.CharField(default='Full arena & events', max_length=100)),
                ('events_description', models.TextField()),
                ('events_cta_label', models.CharField(default='Contact us', max_length=50)),
                ('events_cta_href', models.CharField(default='/contact', max_length=200)),
                ('events_cta_style', models.CharField(default='outline', max_length=20)),
            ],
            options={
                'verbose_name': 'Bookings Rates Section',
                'verbose_name_plural': 'Bookings Rates Section',
                'db_table': 'cms_bookings_rates_section',
            },
        ),
        migrations.CreateModel(
            name='BookingsStep',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key', models.CharField(db_index=True, max_length=50, unique=True)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('sort_order', models.PositiveIntegerField(db_index=True, default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Bookings Step',
                'verbose_name_plural': 'Bookings Steps',
                'db_table': 'cms_bookings_step',
                'ordering': ['sort_order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='BookingsStepsSection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('heading', models.CharField(default='How booking works', max_length=100)),
            ],
            options={
                'verbose_name': 'Bookings Steps Section',
                'verbose_name_plural': 'Bookings Steps Section',
                'db_table': 'cms_bookings_steps_section',
            },
        ),
    ]
