# Generated by Django 5.2.17 on 2026-09-11 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeroSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_one', models.CharField(help_text='First line of title', max_length=200)),
                ('title_two', models.CharField(help_text='Second line of title', max_length=200)),
                ('description', models.TextField(help_text='Hero description text')),
                ('image', models.ImageField(blank=True, help_text='Hero background image', null=True, upload_to='hero/')),
                ('stat_open_label', models.CharField(default='Open every day', help_text='Stat 1 label', max_length=100)),
                ('stat_open_value', models.CharField(default='7 Days/Week', help_text='Stat 1 value', max_length=50)),
                ('stat_matches_label', models.CharField(default='Matches hosted', help_text='Stat 2 label', max_length=100)),
                ('stat_matches_value', models.CharField(default='500+', help_text='Stat 2 value', max_length=50)),
                ('stat_courts_label', models.CharField(default='Premium courts', help_text='Stat 3 label', max_length=100)),
                ('stat_courts_value', models.CharField(default='2 Courts', help_text='Stat 3 value', max_length=50)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Hero Section',
                'verbose_name_plural': 'Hero Section',
            },
        ),
    ]
