# Generated by Django 5.2.17 on 2026-09-10 11:24

import common.storages
import common.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0002_bookingsbanner_bookingshelpstrip_bookingspagemeta_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key', models.CharField(db_index=True, help_text="Uppercase enum (e.g., 'ALL', 'VENUE', 'MATCHES')", max_length=50, unique=True)),
                ('label', models.CharField(help_text="Display label (e.g., 'All', 'Our Venue')", max_length=100)),
                ('sort_order', models.PositiveIntegerField(db_index=True, default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Gallery Category',
                'verbose_name_plural': 'Gallery Categories',
                'db_table': 'cms_gallery_category',
                'ordering': ['sort_order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='GalleryCTA',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('heading', models.CharField(default='Pictures are nice. Playing is nicer.', max_length=200)),
                ('description', models.TextField()),
                ('button_label', models.CharField(default='Book a Slot', max_length=50)),
                ('button_href', models.CharField(default='/bookings', max_length=200)),
                ('button_style', models.CharField(default='primary', max_length=20)),
            ],
            options={
                'verbose_name': 'Gallery CTA',
                'verbose_name_plural': 'Gallery CTA',
                'db_table': 'cms_gallery_cta',
            },
        ),
        migrations.CreateModel(
            name='GalleryHeader',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('eyebrow', models.CharField(default='Gallery', max_length=50)),
                ('title', models.CharField(default='The arena, up close', max_length=200)),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name': 'Gallery Header',
                'verbose_name_plural': 'Gallery Header',
                'db_table': 'cms_gallery_header',
            },
        ),
        migrations.CreateModel(
            name='GalleryPageMeta',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('meta_title', models.CharField(default='Gallery — Nexus FMS', max_length=200)),
                ('meta_description', models.TextField(default='Photos and clips from the Nexus Futsal community — match nights, coaching mornings and the turf itself.', max_length=300)),
            ],
            options={
                'verbose_name': 'Gallery Page Meta',
                'verbose_name_plural': 'Gallery Page Meta',
                'db_table': 'cms_gallery_page_meta',
            },
        ),
        migrations.CreateModel(
            name='GalleryVideosSection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('heading', models.CharField(default='Highlights & clips', max_length=100)),
                ('description', models.TextField(default='Short clips from around the arena — press play.')),
            ],
            options={
                'verbose_name': 'Gallery Videos Section',
                'verbose_name_plural': 'Gallery Videos Section',
                'db_table': 'cms_gallery_videos_section',
            },
        ),
        migrations.CreateModel(
            name='GalleryPhoto',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key', models.CharField(db_index=True, max_length=50, unique=True)),
                ('image', models.ImageField(storage=common.storages.image_storage, upload_to='cms/gallery/photos/', validators=[common.validators.validate_image_upload])),
                ('alt_text', models.CharField(help_text='Alt text for accessibility', max_length=200)),
                ('title', models.CharField(help_text='Title shown on hover', max_length=200)),
                ('category', models.CharField(db_index=True, help_text="Category key (e.g., 'VENUE', 'MATCHES')", max_length=50)),
                ('aspect_ratio', models.CharField(default='4/3', help_text="e.g., '16/10', '4/3', '1/1', '3/4'", max_length=10)),
                ('sort_order', models.PositiveIntegerField(db_index=True, default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Gallery Photo',
                'verbose_name_plural': 'Gallery Photos',
                'db_table': 'cms_gallery_photo',
                'ordering': ['sort_order', 'created_at'],
                'indexes': [models.Index(fields=['category', 'is_active'], name='cms_gallery_categor_f9b971_idx')],
            },
        ),
        migrations.CreateModel(
            name='GalleryVideo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key', models.CharField(db_index=True, max_length=50, unique=True)),
                ('video', models.FileField(storage=common.storages.video_storage, upload_to='cms/gallery/videos/', validators=[common.validators.validate_video_upload])),
                ('poster', models.ImageField(help_text='Video thumbnail/poster', storage=common.storages.image_storage, upload_to='cms/gallery/posters/', validators=[common.validators.validate_image_upload])),
                ('title', models.CharField(max_length=200)),
                ('category', models.CharField(db_index=True, help_text="Category key (e.g., 'VENUE', 'MATCHES')", max_length=50)),
                ('duration_seconds', models.PositiveIntegerField(help_text='Video duration in seconds')),
                ('sort_order', models.PositiveIntegerField(db_index=True, default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Gallery Video',
                'verbose_name_plural': 'Gallery Videos',
                'db_table': 'cms_gallery_video',
                'ordering': ['sort_order', 'created_at'],
                'indexes': [models.Index(fields=['category', 'is_active'], name='cms_gallery_categor_aea676_idx')],
            },
        ),
    ]
