# Generated by Django 5.2.17 on 2026-09-10 13:27

import common.storages
import common.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0003_gallerycategory_gallerycta_galleryheader_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutCommunity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('eyebrow', models.CharField(default='Community', max_length=100)),
                ('heading', models.CharField(default='The arena fills up long before kickoff', max_length=200)),
                ('description', models.TextField()),
                ('image', models.ImageField(storage=common.storages.image_storage, upload_to='cms/about/community/', validators=[common.validators.validate_image_upload])),
                ('image_alt', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'About Community',
                'verbose_name_plural': 'About Community',
                'db_table': 'cms_about_community',
            },
        ),
        migrations.CreateModel(
            name='AboutCommunityBullet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('text', models.TextField()),
                ('sort_order', models.PositiveIntegerField(db_index=True, default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'About Community Bullet',
                'verbose_name_plural': 'About Community Bullets',
                'db_table': 'cms_about_community_bullet',
                'ordering': ['sort_order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='AboutCTA',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('heading', models.CharField(default='Come see the turf for yourself', max_length=200)),
                ('description', models.TextField()),
                ('primary_cta_label', models.CharField(default='Book a Slot', max_length=50)),
                ('primary_cta_href', models.CharField(default='/bookings', max_length=200)),
                ('primary_cta_style', models.CharField(default='secondary', max_length=20)),
                ('secondary_cta_label', models.CharField(default='Contact Us', max_length=50)),
                ('secondary_cta_href', models.CharField(default='/contact', max_length=200)),
                ('secondary_cta_style', models.CharField(default='outline', max_length=20)),
            ],
            options={
                'verbose_name': 'About CTA',
                'verbose_name_plural': 'About CTA',
                'db_table': 'cms_about_cta',
            },
        ),
        migrations.CreateModel(
            name='AboutHero',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('eyebrow', models.CharField(default='About us', max_length=100)),
                ('title', models.CharField(default='More than a court.', max_length=200)),
                ('title_highlight', models.CharField(default='A community.', max_length=200)),
                ('description', models.TextField()),
                ('image', models.ImageField(storage=common.storages.image_storage, upload_to='cms/about/hero/', validators=[common.validators.validate_image_upload])),
                ('image_alt', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'About Hero',
                'verbose_name_plural': 'About Hero',
                'db_table': 'cms_about_hero',
            },
        ),
        migrations.CreateModel(
            name='AboutMilestone',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key', models.CharField(db_index=True, max_length=50, unique=True)),
                ('year', models.CharField(help_text="e.g., '2018', '2021'", max_length=10)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('image', models.ImageField(storage=common.storages.image_storage, upload_to='cms/about/milestones/', validators=[common.validators.validate_image_upload])),
                ('image_alt', models.CharField(max_length=200)),
                ('sort_order', models.PositiveIntegerField(db_index=True, default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'About Milestone',
                'verbose_name_plural': 'About Milestones',
                'db_table': 'cms_about_milestone',
                'ordering': ['sort_order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='AboutPageMeta',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('meta_title', models.CharField(default='About Us — Nexus FMS', max_length=200)),
                ('meta_description', models.TextField(default="Since 2018, Nexus Futsal has been Kathmandu's home of futsal. Meet the team, the story and the community behind the turf.", max_length=300)),
            ],
            options={
                'verbose_name': 'About Page Meta',
                'verbose_name_plural': 'About Page Meta',
                'db_table': 'cms_about_meta',
            },
        ),
        migrations.CreateModel(
            name='AboutStat',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key', models.CharField(db_index=True, help_text="e.g., 'years', 'matches'", max_length=50, unique=True)),
                ('value', models.CharField(help_text="e.g., '8+', '20K+'", max_length=50)),
                ('label', models.CharField(help_text="e.g., 'Years in the game'", max_length=100)),
                ('sort_order', models.PositiveIntegerField(db_index=True, default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'About Stat',
                'verbose_name_plural': 'About Stats',
                'db_table': 'cms_about_stat',
                'ordering': ['sort_order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='AboutStory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('eyebrow', models.CharField(default='Our story', max_length=100)),
                ('heading', models.CharField(default='Built by players, for players', max_length=200)),
                ('description', models.TextField()),
                ('timeline_heading', models.CharField(default='The journey so far', max_length=200)),
                ('timeline_hint', models.CharField(blank=True, default='Drag the cards or use the arrows — the story continues →', max_length=300)),
            ],
            options={
                'verbose_name': 'About Story',
                'verbose_name_plural': 'About Story',
                'db_table': 'cms_about_story',
            },
        ),
        migrations.CreateModel(
            name='AboutTeam',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('eyebrow', models.CharField(default='The team', max_length=100)),
                ('heading', models.CharField(default='The people behind the turf', max_length=200)),
                ('description', models.TextField(default="Say hi when you see us at the counter — we're usually around.")),
            ],
            options={
                'verbose_name': 'About Team',
                'verbose_name_plural': 'About Team',
                'db_table': 'cms_about_team',
            },
        ),
        migrations.CreateModel(
            name='AboutTeamMember',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key', models.CharField(db_index=True, max_length=50, unique=True)),
                ('full_name', models.CharField(max_length=200)),
                ('role', models.CharField(max_length=200)),
                ('profile_image', models.ImageField(blank=True, help_text='Leave blank to show initials avatar', null=True, storage=common.storages.image_storage, upload_to='cms/about/team/', validators=[common.validators.validate_image_upload])),
                ('sort_order', models.PositiveIntegerField(db_index=True, default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'About Team Member',
                'verbose_name_plural': 'About Team Members',
                'db_table': 'cms_about_team_member',
                'ordering': ['sort_order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='AboutValue',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key', models.CharField(db_index=True, help_text="e.g., 'community', 'facilities'", max_length=50, unique=True)),
                ('icon', models.CharField(help_text="Icon name from shared registry, e.g., 'heart-handshake'", max_length=50)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('sort_order', models.PositiveIntegerField(db_index=True, default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'About Value',
                'verbose_name_plural': 'About Values',
                'db_table': 'cms_about_value',
                'ordering': ['sort_order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='AboutValues',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('eyebrow', models.CharField(default='What we stand for', max_length=100)),
                ('heading', models.CharField(default='The values on our badge', max_length=200)),
            ],
            options={
                'verbose_name': 'About Values',
                'verbose_name_plural': 'About Values',
                'db_table': 'cms_about_values',
            },
        ),
    ]
