# Generated by Django 5.2.17 on 2026-09-11 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0003_carouselimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArenaSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Arena section title', max_length=200)),
                ('description', models.TextField(help_text='Arena description text')),
                ('features', models.JSONField(blank=True, default=list, help_text='Array of feature strings')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Arena Section',
                'verbose_name_plural': 'Arena Section',
            },
        ),
    ]
