# Generated by Django 5.2.17 on 2026-09-11 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0004_arenasection'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhyUsSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Why us section title', max_length=200)),
                ('description', models.TextField(help_text='Why us description text')),
                ('features', models.JSONField(blank=True, default=list, help_text='Array of feature objects with iconcode, title, and description')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Why Us Section',
                'verbose_name_plural': 'Why Us Section',
            },
        ),
    ]
