# Generated by Django 5.2.17 on 2026-09-10 13:42

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0004_aboutcommunity_aboutcommunitybullet_aboutcta_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactBookingCard',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(default='Looking to book instead?', max_length=200)),
                ('description', models.TextField(default='Skip the queue — pick your slot online and pay at the counter.')),
                ('cta_label', models.CharField(default='Book a Slot', max_length=50)),
                ('cta_href', models.CharField(default='/bookings', max_length=200)),
                ('cta_style', models.CharField(default='primary', max_length=20)),
            ],
            options={
                'verbose_name': 'Contact Booking Card',
                'verbose_name_plural': 'Contact Booking Card',
                'db_table': 'cms_contact_booking_card',
            },
        ),
        migrations.CreateModel(
            name='ContactDetailItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key', models.CharField(db_index=True, max_length=50, unique=True)),
                ('item_type', models.CharField(choices=[('VISIT', 'Visit'), ('CALL', 'Call'), ('EMAIL', 'Email'), ('HOURS', 'Hours')], db_index=True, help_text='Controls icon + link behavior', max_length=20)),
                ('label', models.CharField(max_length=100)),
                ('hint', models.CharField(blank=True, help_text='Small muted line under the value (optional)', max_length=300)),
                ('value_source', models.CharField(help_text="Documentation: which futsal field feeds the value (e.g., 'futsal.phone')", max_length=200)),
                ('sort_order', models.PositiveIntegerField(db_index=True, default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Contact Detail Item',
                'verbose_name_plural': 'Contact Detail Items',
                'db_table': 'cms_contact_detail_item',
                'ordering': ['sort_order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='ContactDetails',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('heading', models.CharField(default='Reach us directly', max_length=200)),
                ('description', models.TextField(default='The counter is staffed whenever the lights are on.')),
                ('maps_label', models.CharField(default='Get directions', max_length=100)),
            ],
            options={
                'verbose_name': 'Contact Details',
                'verbose_name_plural': 'Contact Details',
                'db_table': 'cms_contact_details',
            },
        ),
        migrations.CreateModel(
            name='ContactForm',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('heading', models.CharField(default='Send us a message', max_length=200)),
                ('description', models.TextField(default='Fill in the form below — we usually reply within a couple of hours.')),
                ('submit_label', models.CharField(default='Send Message', max_length=50)),
                ('submitting_label', models.CharField(default='Sending…', max_length=50)),
                ('success_title', models.CharField(default='Message sent!', max_length=200)),
                ('success_description', models.TextField(default="Thanks {first_name} — we'll reply to {email} within a few hours during opening times.", help_text='Supports tokens: {first_name}, {email}')),
                ('again_label', models.CharField(default='Send another message', max_length=50)),
                ('name_label', models.CharField(default='Full name', max_length=100)),
                ('name_placeholder', models.CharField(default='Enter your full name', max_length=200)),
                ('email_label', models.CharField(default='Email', max_length=100)),
                ('email_placeholder', models.CharField(default='you@example.com', max_length=200)),
                ('phone_label', models.CharField(default='Phone number', max_length=100)),
                ('phone_placeholder', models.CharField(default='10-digit mobile number', max_length=200)),
                ('subject_label', models.CharField(default='Subject', max_length=100)),
                ('subject_placeholder', models.CharField(default='e.g. Corporate event on a Saturday', max_length=200)),
                ('message_label', models.CharField(default='Message', max_length=100)),
                ('message_placeholder', models.CharField(default="Tell us what's on your mind", max_length=200)),
            ],
            options={
                'verbose_name': 'Contact Form',
                'verbose_name_plural': 'Contact Form',
                'db_table': 'cms_contact_form',
            },
        ),
        migrations.CreateModel(
            name='ContactHeader',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('eyebrow', models.CharField(default='Contact Us', max_length=100)),
                ('title', models.CharField(default="We'd love to hear from you", max_length=200)),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name': 'Contact Header',
                'verbose_name_plural': 'Contact Header',
                'db_table': 'cms_contact_header',
            },
        ),
        migrations.CreateModel(
            name='ContactPageMeta',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('meta_title', models.CharField(default='Contact Us — Nexus FMS', max_length=200)),
                ('meta_description', models.TextField(default='Questions about bookings, events or coaching? Reach the Nexus Futsal team by phone, email or the contact form.', max_length=300)),
            ],
            options={
                'verbose_name': 'Contact Page Meta',
                'verbose_name_plural': 'Contact Page Meta',
                'db_table': 'cms_contact_meta',
            },
        ),
    ]
