# Generated by Django 5.2.17 on 2026-09-11 13:14

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0005_whyussection'),
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text="Category name (e.g., 'Tournaments', 'Facilities', 'Events')", max_length=100, unique=True)),
                ('slug', models.SlugField(help_text='URL-friendly version of name', max_length=100, unique=True)),
                ('description', models.TextField(blank=True, default='', help_text='Optional category description')),
                ('is_active', models.BooleanField(default=True, help_text='Show category on website')),
                ('sort_order', models.IntegerField(default=0, help_text='Display order (lower numbers first)')),
            ],
            options={
                'verbose_name': 'Gallery Category',
                'verbose_name_plural': 'Gallery Categories',
                'db_table': 'cms_gallery_category',
                'ordering': ['sort_order', 'name'],
            },
        ),
    ]
