# Generated by Django 5.2.17 on 2026-09-11 13:22

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0006_gallerycategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(help_text='Image title', max_length=200)),
                ('image', models.ImageField(help_text='Gallery image', upload_to='gallery/')),
                ('alt_text', models.CharField(help_text='Alt text for accessibility', max_length=200)),
                ('is_active', models.BooleanField(default=True, help_text='Show on website')),
                ('sort_order', models.IntegerField(default=0, help_text='Display order within category')),
                ('category', models.ForeignKey(help_text='Gallery category', on_delete=django.db.models.deletion.CASCADE, related_name='images', to='cms.gallerycategory')),
            ],
            options={
                'verbose_name': 'Gallery Image',
                'verbose_name_plural': 'Gallery Images',
                'db_table': 'cms_gallery_image',
                'ordering': ['category', 'sort_order', 'created_at'],
                'indexes': [models.Index(fields=['category', 'is_active'], name='cms_gallery_categor_15bc96_idx'), models.Index(fields=['category', 'sort_order'], name='cms_gallery_categor_4e50ab_idx')],
            },
        ),
    ]
