# Generated by Django 5.2.17 on 2026-09-11 13:28

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0007_galleryimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryHighlight',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(help_text='Video title', max_length=200)),
                ('video', models.FileField(help_text='Highlight video (Cloudinary)', upload_to='highlights/')),
                ('tags', models.JSONField(blank=True, default=list, help_text="Array of tag strings (e.g., ['goal', 'save', 'skills'])")),
                ('thumbnail', models.ImageField(blank=True, help_text='Video thumbnail (optional)', null=True, upload_to='highlights/thumbnails/')),
                ('is_active', models.BooleanField(default=True, help_text='Show on website')),
                ('sort_order', models.IntegerField(default=0, help_text='Display order')),
            ],
            options={
                'verbose_name': 'Gallery Highlight',
                'verbose_name_plural': 'Gallery Highlights',
                'db_table': 'cms_gallery_highlight',
                'ordering': ['sort_order', '-created_at'],
                'indexes': [models.Index(fields=['is_active', 'sort_order'], name='cms_gallery_is_acti_38d1a5_idx')],
            },
        ),
    ]
