# Generated by Django 5.2.17 on 2026-09-11 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0008_galleryhighlight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='galleryhighlight',
            name='tags',
            field=models.TextField(blank=True, default='', help_text="Tags for the video (e.g., 'goal, save, skills')"),
        ),
    ]
