# Generated by Django 5.2.17 on 2026-09-11 16:51

import common.storages
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0009_alter_galleryhighlight_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='galleryhighlight',
            name='thumbnail',
            field=models.ImageField(blank=True, help_text='Video thumbnail (optional)', null=True, storage=common.storages.image_storage, upload_to='highlights/thumbnails/'),
        ),
        migrations.AlterField(
            model_name='galleryhighlight',
            name='video',
            field=models.FileField(help_text='Highlight video (Cloudinary)', storage=common.storages.video_storage, upload_to='highlights/'),
        ),
    ]
