# Generated by Django 5.2.17 on 2026-09-11 17:07

import common.storages
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0010_alter_galleryhighlight_thumbnail_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carouselimage',
            name='image',
            field=models.ImageField(help_text='Carousel image', storage=common.storages.image_storage, upload_to='carousel/'),
        ),
        migrations.AlterField(
            model_name='galleryimage',
            name='image',
            field=models.ImageField(help_text='Gallery image', storage=common.storages.image_storage, upload_to='gallery/'),
        ),
        migrations.AlterField(
            model_name='herosection',
            name='image',
            field=models.ImageField(blank=True, help_text='Hero background image', null=True, storage=common.storages.image_storage, upload_to='hero/'),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='image',
            field=models.ImageField(blank=True, help_text='Customer photo', null=True, storage=common.storages.image_storage, upload_to='testimonials/'),
        ),
    ]
