# Generated by Django 5.2.17 on 2026-09-12 04:07

import common.storages
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0012_ensure_testimonial_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutHeroSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='About hero section title', max_length=200)),
                ('description', models.TextField(help_text='About hero description text')),
                ('image', models.ImageField(blank=True, help_text='About hero background image', null=True, storage=common.storages.image_storage, upload_to='about/hero/')),
                ('years_in_game', models.IntegerField(default=0, help_text='Years in the game')),
                ('matches_hosted', models.IntegerField(default=0, help_text='Matches hosted')),
                ('tournaments_run', models.IntegerField(default=0, help_text='Tournaments run')),
                ('players_in_community', models.IntegerField(default=0, help_text='Players in the community')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'About Hero Section',
                'verbose_name_plural': 'About Hero Section',
            },
        ),
    ]
