# Generated by Django 5.2.17 on 2026-09-12 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0013_add_about_hero_section'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutStory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Story section title', max_length=200)),
                ('description', models.TextField(help_text='Story description text')),
                ('journey', models.JSONField(blank=True, default=list, help_text='Array of journey milestones with year, title, description, and image')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'About Story Section',
                'verbose_name_plural': 'About Story Section',
            },
        ),
    ]
