# Generated by Django 5.2.17 on 2026-09-12 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0014_add_about_story'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutCommunity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Community section title', max_length=200)),
                ('description', models.TextField(help_text='Community description text')),
                ('features', models.JSONField(blank=True, default=list, help_text='Array of feature strings')),
                ('team', models.JSONField(blank=True, default=list, help_text='Array of team members with name, role, and image')),
                ('rules', models.JSONField(blank=True, default=list, help_text='Array of rules with iconcode, title, and description')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'About Community Section',
                'verbose_name_plural': 'About Community Section',
            },
        ),
    ]
