# Generated by Django 5.2.17 on 2026-09-12 04:26

import common.storages
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0015_add_about_community'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingsHeroSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Bookings hero section title', max_length=200)),
                ('description', models.TextField(help_text='Bookings hero description text')),
                ('image', models.ImageField(blank=True, help_text='Bookings hero background image', null=True, storage=common.storages.image_storage, upload_to='bookings/hero/')),
                ('info', models.JSONField(blank=True, default=list, help_text='Array of info items with iconcode, title, and description')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Bookings Hero Section',
                'verbose_name_plural': 'Bookings Hero Section',
            },
        ),
    ]
