# Generated by Django 5.2.17 on 2026-09-12 05:02

import common.storages
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0016_add_bookings_hero_section'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutcommunity',
            name='image',
            field=models.ImageField(blank=True, help_text='About community background image', null=True, storage=common.storages.image_storage, upload_to='about/community/'),
        ),
        migrations.AddField(
            model_name='aboutstory',
            name='image',
            field=models.ImageField(blank=True, help_text='About story background image', null=True, storage=common.storages.image_storage, upload_to='about/story/'),
        ),
    ]
