# Generated by Django 5.2.17 on 2026-09-12 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0017_add_image_to_about_sections'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutherosection',
            name='matches_hosted',
            field=models.CharField(default='0', help_text='Matches hosted', max_length=50),
        ),
        migrations.AlterField(
            model_name='aboutherosection',
            name='players_in_community',
            field=models.CharField(default='0', help_text='Players in the community', max_length=50),
        ),
        migrations.AlterField(
            model_name='aboutherosection',
            name='tournaments_run',
            field=models.CharField(default='0', help_text='Tournaments run', max_length=50),
        ),
        migrations.AlterField(
            model_name='aboutherosection',
            name='years_in_game',
            field=models.CharField(default='0', help_text='Years in the game', max_length=50),
        ),
    ]
