# Generated by Django 5.2.17 on 2026-09-13

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cms", "0018_change_about_hero_stats_to_string"),
    ]

    operations = [
        migrations.CreateModel(
            name="FAQ",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("question", models.CharField(help_text="Frequently asked question", max_length=500)),
                ("answer", models.TextField(help_text="Answer to the question")),
            ],
            options={
                "verbose_name": "FAQ",
                "verbose_name_plural": "FAQs",
                "db_table": "cms_faq",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="TermsAndPrivacy",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("terms", models.TextField(blank=True, default="", help_text="Terms and conditions content")),
                ("privacy", models.TextField(blank=True, default="", help_text="Privacy policy content")),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Terms and Privacy",
                "verbose_name_plural": "Terms and Privacy",
            },
        ),
    ]
