# Generated by Django 5.2.17 on 2026-09-04 02:22

import common.storages
import common.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_seed_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, storage=common.storages.image_storage, upload_to='profiles/', validators=[common.validators.validate_image_upload]),
        ),
    ]
