# Generated by Django 6.1.1 on 2026-09-03 07:49

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Futsal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True, default='')),
                ('location', models.CharField(max_length=150)),
                ('address', models.CharField(blank=True, default='', max_length=255)),
                ('phone', models.CharField(blank=True, default='', max_length=20)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('price_per_slot', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('slot_duration', models.PositiveIntegerField(default=60, help_text='Minutes')),
                ('opening_time', models.TimeField()),
                ('closing_time', models.TimeField()),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive')], db_index=True, default='ACTIVE', max_length=10)),
            ],
            options={
                'db_table': 'futsal_futsal',
                'ordering': ['name'],
                'constraints': [models.CheckConstraint(condition=models.Q(('price_per_slot__gte', 0)), name='futsal_price_non_negative')],
            },
        ),
        migrations.CreateModel(
            name='Slot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField(db_index=True)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('price', models.DecimalField(blank=True, decimal_places=2, help_text='Overrides futsal price when set.', max_digits=10, null=True)),
                ('status', models.CharField(choices=[('AVAILABLE', 'Available'), ('BOOKED', 'Booked'), ('BLOCKED', 'Blocked')], db_index=True, default='AVAILABLE', max_length=10)),
                ('futsal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='futsal.futsal')),
            ],
            options={
                'db_table': 'futsal_slot',
                'ordering': ['date', 'start_time'],
                'indexes': [models.Index(fields=['date', 'status'], name='futsal_slot_date_e8f2a2_idx'), models.Index(fields=['futsal', 'date', 'status'], name='futsal_slot_futsal__acbed0_idx')],
                'constraints': [models.UniqueConstraint(fields=('futsal', 'date', 'start_time'), name='uniq_slot_per_futsal_datetime'), models.CheckConstraint(condition=models.Q(('start_time__lt', models.F('end_time'))), name='slot_start_before_end')],
            },
        ),
    ]
