# Generated by Django 6.1.1 on 2026-09-03 08:09

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('futsal', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FutsalClosure',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField(db_index=True)),
                ('reason', models.CharField(blank=True, default='', max_length=255)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='futsal_closures', to=settings.AUTH_USER_MODEL)),
                ('futsal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='closures', to='futsal.futsal')),
            ],
            options={
                'db_table': 'futsal_closure',
                'ordering': ['-date'],
                'constraints': [models.UniqueConstraint(fields=('futsal', 'date'), name='uniq_closure_per_date')],
            },
        ),
    ]
