# Generated by Django 5.2.17 on 2026-09-04 02:22

import common.storages
import common.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('futsal', '0002_futsalclosure'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FutsalMedia',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('media_type', models.CharField(choices=[('IMAGE', 'Image'), ('VIDEO', 'Video')], db_index=True, default='IMAGE', max_length=5)),
                ('image', models.ImageField(blank=True, null=True, storage=common.storages.image_storage, upload_to='futsal/images/', validators=[common.validators.validate_image_upload])),
                ('video', models.FileField(blank=True, null=True, storage=common.storages.video_storage, upload_to='futsal/videos/', validators=[common.validators.validate_video_upload])),
                ('caption', models.CharField(blank=True, default='', max_length=255)),
                ('is_cover', models.BooleanField(default=False)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('futsal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='futsal.futsal')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_media', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'futsal_media',
                'ordering': ['sort_order', '-created_at'],
                'indexes': [models.Index(fields=['futsal', 'media_type'], name='futsal_medi_futsal__81dcf3_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('media_type', 'IMAGE'), models.Q(('image__in', ['', None]), _negated=True), ('video__in', ['', None])), models.Q(('media_type', 'VIDEO'), models.Q(('video__in', ['', None]), _negated=True), ('image__in', ['', None])), _connector='OR'), name='media_matches_declared_type')],
            },
        ),
    ]
