# Generated by Django 5.2.17 on 2026-09-11 02:24

import datetime as dt
from django.db import migrations


def ensure_futsal_hours(apps, schema_editor):
    """Ensure Futsal singleton has opening and closing times set."""
    Futsal = apps.get_model('futsal', 'Futsal')
    
    # Get or create the singleton
    futsal = Futsal.objects.first()
    if not futsal:
        # Create singleton with default times
        Futsal.objects.create(
            name="Futsal Arena",
            opening_time=dt.time(6, 0),  # 6:00 AM
            closing_time=dt.time(22, 0),  # 10:00 PM
            price_per_slot=1500,
            slot_duration=60,
        )
    else:
        # Update existing singleton if times are missing
        updated = False
        if not futsal.opening_time:
            futsal.opening_time = dt.time(6, 0)
            updated = True
        if not futsal.closing_time:
            futsal.closing_time = dt.time(22, 0)
            updated = True
        if updated:
            futsal.save(update_fields=['opening_time', 'closing_time'])


class Migration(migrations.Migration):

    dependencies = [
        ('futsal', '0003_futsalmedia'),
    ]

    operations = [
        migrations.RunPython(ensure_futsal_hours, migrations.RunPython.noop),
    ]
