# Generated by Django 5.2.17 on 2026-09-11 13:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('futsal', '0004_ensure_futsal_hours'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facebook', models.URLField(blank=True, default='', help_text='Facebook page URL', validators=[django.core.validators.URLValidator()])),
                ('instagram', models.URLField(blank=True, default='', help_text='Instagram profile URL', validators=[django.core.validators.URLValidator()])),
                ('twitter', models.URLField(blank=True, default='', help_text='Twitter/X profile URL', validators=[django.core.validators.URLValidator()])),
                ('tiktok', models.URLField(blank=True, default='', help_text='TikTok profile URL', validators=[django.core.validators.URLValidator()])),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Social Media',
                'verbose_name_plural': 'Social Media',
                'db_table': 'futsal_social_media',
            },
        ),
    ]
