# Generated by Django 5.2.17 on 2026-09-11 13:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('futsal', '0005_socialmedia'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SocialMedia',
        ),
        migrations.AddField(
            model_name='futsal',
            name='facebook',
            field=models.URLField(blank=True, default='', help_text='Facebook page URL', validators=[django.core.validators.URLValidator()]),
        ),
        migrations.AddField(
            model_name='futsal',
            name='instagram',
            field=models.URLField(blank=True, default='', help_text='Instagram profile URL', validators=[django.core.validators.URLValidator()]),
        ),
        migrations.AddField(
            model_name='futsal',
            name='tiktok',
            field=models.URLField(blank=True, default='', help_text='TikTok profile URL', validators=[django.core.validators.URLValidator()]),
        ),
        migrations.AddField(
            model_name='futsal',
            name='twitter',
            field=models.URLField(blank=True, default='', help_text='Twitter/X profile URL', validators=[django.core.validators.URLValidator()]),
        ),
    ]
