# Generated by Django 6.1.1 on 2026-09-03 07:49

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reminder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reminder_type', models.CharField(choices=[('AUTOMATIC_ONE_HOUR', 'Automatic one hour'), ('MANUAL', 'Manual')], db_index=True, max_length=32)),
                ('scheduled_at', models.DateTimeField()),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SENT', 'Sent'), ('FAILED', 'Failed')], db_index=True, default='PENDING', max_length=10)),
                ('error_message', models.TextField(blank=True, default='')),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='bookings.booking')),
                ('triggered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='triggered_reminders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'notifications_reminder',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'scheduled_at'], name='notificatio_status_84d5a7_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('reminder_type', 'AUTOMATIC_ONE_HOUR')), fields=('booking', 'reminder_type'), name='uniq_automatic_reminder_per_booking')],
            },
        ),
    ]
